spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/influx-v1
    username: postgres
    password: Bartek12.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


