spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/influx-v1
    username: postgres
    password: Bartek12.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}


application:
  security:
    jwt:
      secret-key: 9aeab6643d73b7e2d210471a3e82112b074271226e5d1b17411f3413c925097b
      expiration: 86400000



EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ADDRESS: springinflux@gmail.com
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:8080